---
- name: restart-apache
  service: name=apache2 state=restarted

- name: chown-everything
  file:
    owner: www-data
    group: www-data
    path: /usr/local/phonebocx
    state: directory
    recurse: true
